server:
  port: 8084

spring:
   cloud:
    gateway:
     routes:



      #Route Mapping
       - id: CouponService
         uri: http://localhost:8081/
         predicates:
         - Path=/coupon/**

      #Route Mapping
       - id: ProductsService
         uri: http://localhost:8092/
         predicates:
         - Path=/products/**


         #Route Mapping
       - id: CartService
         uri: http://localhost:8082/
         predicates:
         - Path=/cart/**

       #Route Mapping
       - id: ProfileService
         uri: http://localhost:8080/
         predicates:
           - Path=/profile/**